# Generated by Django 6.1.1 on 2026-09-16 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Internal machine name, e.g. medical_certificate.', max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('richtext', 'Rich Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes / No'), ('select', 'Dropdown (single choice)'), ('multiselect', 'Multiple choice'), ('file', 'File Upload')], max_length=20)),
                ('required', models.BooleanField(default=False, help_text='HR is required to complete this item.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('group', models.CharField(blank=True, help_text='Section heading used to group related attributes in the form.', max_length=120)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Optional JSON rules. number/date: {"min": ..., "max": ...}. text: {"min_length": ..., "max_length": ..., "regex": ...}. file: {"max_size_mb": ...}.')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Optional conditional display logic: {"depends_on": "<attribute name>", "operator": "equals|not_equals|in", "value": "x" or ["a","b"]}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color used for the badge in the HR list.', max_length=20, verbose_name='Badge color')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAttrOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='leave.leaveattribute')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, help_text='Short summary HR sees at a glance.', max_length=255, verbose_name='Reason summary')),
                ('start_date', models.DateField(verbose_name='From')),
                ('end_date', models.DateField(verbose_name='To')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='leaveattribute',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='leave/attachments/%Y/%m/')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaveattribute')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='leave.leaverequest')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'unique_together': {('request', 'attribute')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='leaveattribute',
            unique_together={('leave_type', 'name')},
        ),
    ]
