services:
  web:
    build: .
    image: hannyhr:latest
    container_name: hannyhr-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_ENGINE: sqlite
      DB_NAME: db.sqlite3
    ports:
      - "8050:8000"
    volumes:
      - .:/app
      - media_data:/app/media

volumes:
  media_data: