# Generated by Django 6.1.1 on 2026-09-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_manage_hr', 'Can access the HR management console')], 'verbose_name_plural': 'Employees'},
        ),
    ]
